//! JSON-LD → petgraph DAG loader
//!
//! Deserializes JSON-LD workflow definitions generated by the Web UI and converts them to a petgraph DiGraph.

use std::collections::HashMap;

use petgraph::prelude::*;
use serde_json::Value;
use tracing::{info, warn};

use super::definition::*;

/// Loaded DAG containing petgraph graph and node/edge weight mappings
pub struct WorkflowDag {
    /// petgraph directed graph
    pub graph: DiGraph<GraphNode, GraphEdge>,
    /// Node ID → NodeIndex mapping
    pub node_index: HashMap<String, NodeIndex>,
    /// Entry node index
    pub entry_node: NodeIndex,
}

/// Node weight in the DAG graph
#[derive(Debug, Clone)]
pub struct GraphNode {
    pub def: WorkflowNodeDef,
}

/// Edge weight in the DAG graph
#[derive(Debug, Clone)]
pub struct GraphEdge {
    pub relation: String, // "next" | "dependency" | "branch"
}

/// Load workflow definition from JSON-LD string
///
/// Supports two formats:
/// 1. Direct `WorkflowDefinition` (snake_case field names)
/// 2. `@graph` container (JSON-LD standard format, `wf:`-prefixed field names)
pub fn load_workflow_jsonld(json: &str) -> Result<WorkflowDefinition, String> {
    // Try direct deserialization first (concise format)
    if let Ok(wf) = serde_json::from_str::<WorkflowDefinition>(json) {
        return Ok(wf);
    }

    // try to parse as @graph container
    let root: Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse failed: {}", e))?;

    let graph_array = match root.get("@graph") {
        Some(Value::Array(arr)) => arr,
        _ => return Err("Cannot parse JSON-LD workflow definition: neither WorkflowDefinition nor @graph array".to_string()),
    };

    // Find Workflow definition and AgentNode definitions in @graph array
    let mut workflow_entry: Option<&Value> = None;
    let mut agent_nodes: Vec<&Value> = Vec::new();

    for entry in graph_array {
        match entry.get("@type").and_then(|t| t.as_str()) {
            Some("Workflow") | Some("wf:Workflow") => {
                workflow_entry = Some(entry);
            }
            Some("AgentNode") | Some("wf:AgentNode") => {
                agent_nodes.push(entry);
            }
            _ => {} // Ignore other types
        }
    }

    let wf_entry = workflow_entry.ok_or_else(|| {
        "No entry with @type Workflow found in @graph array".to_string()
    })?;

    // Extract fields from Workflow entry (handle wf: prefix)
    let name = get_jsonld_str(wf_entry, "name")
        .unwrap_or_default();
    let description = get_jsonld_str(wf_entry, "description")
        .unwrap_or_default();
    let version = get_jsonld_str(wf_entry, "version")
        .unwrap_or_default();
    let entry_node = get_jsonld_str(wf_entry, "entryNode")
        .or_else(|| get_jsonld_str(wf_entry, "entry_node"))
        .ok_or_else(|| "Workflow missing entryNode or entry_node".to_string())?;
    let wf_id = get_jsonld_str(wf_entry, "@id")
        .or_else(|| get_jsonld_str(wf_entry, "id"))
        .unwrap_or_else(|| "wf:unnamed".to_string());

    // Get node order and references from Workflow's nodes list
    let wf_node_refs: Vec<String> = get_jsonld_array(wf_entry, "nodes")
        .iter()
        .filter_map(|v| {
            // Nodes can be string @id or objects
            v.as_str().map(|s| s.to_string())
                .or_else(|| v.get("@id").and_then(|id| id.as_str().map(|s| s.to_string())))
        })
        .collect();

    // Collect all AgentNodes, build id → entry mapping
    let mut node_map: HashMap<String, &Value> = HashMap::new();
    for entry in &agent_nodes {
        let nid = get_jsonld_str(entry, "@id")
            .or_else(|| get_jsonld_str(entry, "id"))
            .unwrap_or_default();
        node_map.insert(nid, *entry);
    }

    // Build node list in wf_node_refs order; fall back to agent_nodes order if no references
    let ordered_entries: Vec<&Value> = if wf_node_refs.is_empty() {
        agent_nodes
    } else {
        wf_node_refs.iter()
            .filter_map(|ref_id| {
                let found = node_map.get(ref_id).copied();
                if found.is_none() {
                    warn!("Workflow references node '{}' but not found in @graph", ref_id);
                }
                found
            })
            .collect()
    };

    // Convert each AgentNode entry to WorkflowNodeDef
    let mut nodes = Vec::new();
    for entry in ordered_entries {
        nodes.push(parse_agent_node(entry)?);
    }

    Ok(WorkflowDefinition {
        id: wf_id,
        name,
        description,
        version,
        entry_node,
        nodes,
    })
}

/// Extract string field from JSON-LD value (supports wf: prefix and snake_case)
fn get_jsonld_str(val: &Value, field: &str) -> Option<String> {
    let variants = [
        field.to_string(),
        format!("wf:{}", field),
        field.replace('_', ""),           // entry_node → entrynode
    ];
    for v in &variants {
        if let Some(s) = val.get(v).and_then(|v| v.as_str()) {
            return Some(s.to_string());
        }
    }
    None
}

/// Extract array field from JSON-LD value (supports wf: prefix)
fn get_jsonld_array<'a>(val: &'a Value, field: &str) -> Vec<&'a Value> {
    let variants = [field.to_string(), format!("wf:{}", field)];
    for v in &variants {
        if let Some(Value::Array(arr)) = val.get(v) {
            return arr.iter().collect();
        }
    }
    vec![]
}

/// Extract boolean field from JSON-LD value
fn _get_jsonld_bool(val: &Value, field: &str) -> Option<bool> {
    let variants = [field.to_string(), format!("wf:{}", field)];
    for v in &variants {
        if let Some(b) = val.get(v).and_then(|v| v.as_bool()) {
            return Some(b);
        }
    }
    None
}

/// Extract u64 field from JSON-LD value (supports integers and numeric strings)
fn get_jsonld_u64(val: &Value, field: &str) -> Option<u64> {
    let variants = [field.to_string(), format!("wf:{}", field)];
    for v in &variants {
        if let Some(n) = val.get(v).and_then(|v| v.as_u64()) {
            return Some(n);
        }
        // Also try parsing numeric strings
        if let Some(s) = val.get(v).and_then(|v| v.as_str()) {
            if let Ok(n) = s.parse::<u64>() {
                return Some(n);
            }
        }
    }
    None
}

/// Parse JSON-LD AgentNode entry into WorkflowNodeDef
fn parse_agent_node(entry: &Value) -> Result<WorkflowNodeDef, String> {
    let node_id = get_jsonld_str(entry, "@id")
        .or_else(|| get_jsonld_str(entry, "id"))
        .ok_or_else(|| "AgentNode missing @id".to_string())?;

    let agent_role = get_jsonld_str(entry, "agent_role")
        .or_else(|| get_jsonld_str(entry, "agentRole"))
        .ok_or_else(|| format!("Node {} missing agent_role", node_id))?;

    let objective = get_jsonld_str(entry, "objective").unwrap_or_default();
    let expected_output = get_jsonld_str(entry, "expected_output")
        .or_else(|| get_jsonld_str(entry, "expectedOutput"))
        .unwrap_or_default();
    let success_criteria = get_jsonld_str(entry, "success_criteria")
        .or_else(|| get_jsonld_str(entry, "successCriteria"))
        .unwrap_or_default();

    let node_type = get_jsonld_str(entry, "@type")
        .unwrap_or_else(|| "AgentNode".to_string());

    // Parse string array fields
    let tools = parse_string_array(entry, "tools");
    let dependencies = parse_string_array(entry, "dependencies");
    let next_nodes = parse_string_array(entry, "next_nodes")
        .or_else(|| parse_string_array(entry, "nextNodes"))
        .unwrap_or_default();

    let next = get_jsonld_str(entry, "next");
    let final_node = get_jsonld_str(entry, "final_node")
        .or_else(|| get_jsonld_str(entry, "finalNode"))
        .map(|s| s == "true" || s == "True")
        .unwrap_or(false);

    let retry_count = get_jsonld_u64(entry, "retry_count")
        .or_else(|| get_jsonld_u64(entry, "retryCount"))
        .unwrap_or(0) as u32;
    let retry_delay_secs = get_jsonld_u64(entry, "retry_delay_secs")
        .or_else(|| get_jsonld_u64(entry, "retryDelaySecs"))
        .unwrap_or(0);
    let timeout_secs = get_jsonld_u64(entry, "timeout_secs")
        .or_else(|| get_jsonld_u64(entry, "timeoutSecs"))
        .unwrap_or(0);

    // Parse branch_on_failure
    let branch_on_failure = parse_branch_condition(entry);

    // Parse input_mapping
    let input_mapping = parse_input_mapping(entry);

    // Parse HumanApprovalNode-specific fields
    let approval_prompt = get_jsonld_str(entry, "approval_prompt")
        .or_else(|| get_jsonld_str(entry, "approvalPrompt"))
        .unwrap_or_default();
    let approval_next_on_approve = get_jsonld_str(entry, "approval_next_on_approve")
        .or_else(|| get_jsonld_str(entry, "approvalNextOnApprove"));
    let approval_next_on_reject = get_jsonld_str(entry, "approval_next_on_reject")
        .or_else(|| get_jsonld_str(entry, "approvalNextOnReject"));

    Ok(WorkflowNodeDef {
        id: node_id,
        node_type,
        agent_role,
        objective,
        next,
        next_nodes,
        dependencies: dependencies.unwrap_or_default(),
        tools: tools.unwrap_or_default(),
        expected_output,
        success_criteria,
        approval_prompt,
        approval_next_on_approve,
        approval_next_on_reject,
        input_mapping,
        branch_on_failure,
        retry_count,
        retry_delay_secs,
        timeout_secs,
        final_node,
        extra: Default::default(),
    })
}

/// Parse string array field
fn parse_string_array(entry: &Value, field: &str) -> Option<Vec<String>> {
    let variants = [field.to_string(), format!("wf:{}", field)];
    for v in &variants {
        if let Some(Value::Array(arr)) = entry.get(v) {
            let strs: Vec<String> = arr.iter()
                .filter_map(|item| item.as_str().map(|s| s.to_string()))
                .collect();
            if !strs.is_empty() || !arr.is_empty() {
                return Some(strs);
            }
        }
    }
    None
}

/// Parse branch_on_failure condition
fn parse_branch_condition(entry: &Value) -> Option<BranchCondition> {
    let variants = ["branch_on_failure", "branchOnFailure", "wf:branchOnFailure"];
    for var in &variants {
        if let Some(bf) = entry.get(*var) {
            let condition = bf.get("condition")
                .or_else(|| bf.get("wf:condition"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string());
            let target = bf.get("target")
                .or_else(|| bf.get("wf:target"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string());
            if let (Some(cond), Some(tgt)) = (condition, target) {
                return Some(BranchCondition {
                    condition: cond,
                    target: tgt,
                });
            }
        }
    }
    None
}

/// Parse input_mapping
fn parse_input_mapping(entry: &Value) -> Option<InputMapping> {
    let variants = ["input_mapping", "inputMapping", "wf:inputMapping"];
    for var in &variants {
        if let Some(im) = entry.get(*var) {
            let mappings: HashMap<String, String> = im.get("mappings")
                .or_else(|| im.get("wf:mappings"))
                .and_then(|m| m.as_object())
                .map(|obj| {
                    obj.iter()
                        .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                        .collect()
                })
                .unwrap_or_default();
            let context_template = im.get("context_template")
                .or_else(|| im.get("contextTemplate"))
                .or_else(|| im.get("wf:contextTemplate"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_default();
            if !mappings.is_empty() || !context_template.is_empty() {
                return Some(InputMapping {
                    mappings,
                    context_template,
                });
            }
        }
    }
    None
}

/// Build petgraph DiGraph from WorkflowNodeDef list (auto-infer dependencies)
pub fn build_dag(def: &WorkflowDefinition) -> Result<WorkflowDag, String> {
    let mut graph = DiGraph::<GraphNode, GraphEdge>::new();
    let mut node_index: HashMap<String, NodeIndex> = HashMap::new();

    if def.nodes.is_empty() {
        return Err("No nodes in workflow definition".to_string());
    }

    // Phase 1: Add all nodes
    for node_def in &def.nodes {
        let idx = graph.add_node(GraphNode {
            def: node_def.clone(),
        });
        node_index.insert(node_def.id.clone(), idx);
    }

    // Phase 2: Build edges
    for node_def in &def.nodes {
        let src_idx = node_index.get(&node_def.id).ok_or_else(|| {
            format!("Node {} not found in node_index", node_def.id)
        })?;

        // 2a: next edges (main execution flow)
        if let Some(ref next_id) = node_def.next {
            if let Some(dst_idx) = node_index.get(next_id) {
                graph.add_edge(*src_idx, *dst_idx, GraphEdge {
                    relation: "next".to_string(),
                });
            } else {
                warn!("Node {} next '{}' does not exist", node_def.id, next_id);
            }
        }

        // 2b: next_nodes edges (parallel forks)
        for next_id in &node_def.next_nodes {
            if let Some(dst_idx) = node_index.get(next_id) {
                graph.add_edge(*src_idx, *dst_idx, GraphEdge {
                    relation: "next".to_string(),
                });
            } else {
                warn!("Node {} next_node '{}' does not exist", node_def.id, next_id);
            }
        }

        // 2c: dependencies edges (additional prerequisites)
        for dep_id in &node_def.dependencies {
            if let Some(dep_idx) = node_index.get(dep_id) {
                graph.add_edge(*dep_idx, *src_idx, GraphEdge {
                    relation: "dependency".to_string(),
                });
            }
        }

        // 2d: branch_on_failure edges (skip self-loops — self-loops are runtime retry, not DAG dependencies)
        if let Some(ref branch) = node_def.branch_on_failure {
            if branch.target != node_def.id {
                if let Some(dst_idx) = node_index.get(&branch.target) {
                    graph.add_edge(*src_idx, *dst_idx, GraphEdge {
                        relation: "branch".to_string(),
                    });
                }
            }
        }
    }

    let entry_idx = *node_index.get(&def.entry_node).ok_or_else(|| {
        format!("Entry node '{}' not found in node list", def.entry_node)
    })?;

    info!(
        nodes = def.nodes.len(),
        edges = graph.edge_count(),
        entry = %def.entry_node,
        "DAG build completed"
    );

    Ok(WorkflowDag {
        graph,
        node_index,
        entry_node: entry_idx,
    })
}

/// Detect if the graph contains a cycle
pub fn has_cycle(dag: &WorkflowDag) -> bool {
    petgraph::algo::is_cyclic_directed(&dag.graph)
}

/// Topological sort, returns execution order
pub fn topological_order(dag: &WorkflowDag) -> Result<Vec<NodeIndex>, String> {
    match petgraph::algo::toposort(&dag.graph, None) {
        Ok(order) => Ok(order),
        Err(cycle) => {
            let cycle_node = cycle.node_id();
            let node = &dag.graph[cycle_node];
            Err(format!("Cycle detected involving node: {}", node.def.id))
        }
    }
}

/// Get all predecessors of a node (incoming edge neighbors)
pub fn predecessors(dag: &WorkflowDag, node: NodeIndex) -> Vec<NodeIndex> {
    dag.graph
        .neighbors_directed(node, Incoming)
        .collect()
}

/// Check if all dependencies of a node are met
pub fn all_dependencies_met(
    dag: &WorkflowDag,
    node: NodeIndex,
    completed: &HashMap<String, NodeResult>,
) -> bool {
    for pred in dag.graph.neighbors_directed(node, Incoming) {
        let pred_id = &dag.graph[pred].def.id;
        if !completed.contains_key(pred_id) {
            return false;
        }
    }
    true
}

/// Check if the conditional branch should trigger
pub fn should_branch(
    node_def: &WorkflowNodeDef,
    result: &NodeResult,
) -> Option<String> {
    if let Some(ref branch) = node_def.branch_on_failure {
        let matches = match branch.condition.as_str() {
            "$.result.status == 'failed'" => result.status == "failed",
            "$.result.status == 'success'" => result.status == "success",
            _ => {
                // Simple string matching condition
                let cond = branch.condition.trim();
                result.status == cond || result.summary.contains(cond)
            }
        };
        if matches {
            return Some(branch.target.clone());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_jsonld_workflow() {
        let json = r#"{
            "@id": "wf:test",
            "name": "Test",
            "description": "test",
            "version": "1.0",
            "entry_node": "step_1",
            "nodes": [
                {
                    "@id": "step_1",
                    "@type": "AgentNode",
                    "agent_role": "Plan",
                    "objective": "plan step",
                    "next": "step_2"
                },
                {
                    "@id": "step_2",
                    "@type": "AgentNode",
                    "agent_role": "Do",
                    "objective": "do step",
                    "final_node": true
                }
            ]
        }"#;

        let def = load_workflow_jsonld(json).unwrap();
        assert_eq!(def.nodes.len(), 2);
        assert_eq!(def.entry_node, "step_1");
    }

    #[test]
    fn test_build_dag_linear() {
        let json = r#"{
            "@id": "wf:linear",
            "name": "Linear",
            "description": "linear test",
            "version": "1.0",
            "entry_node": "a",
            "nodes": [
                {"@id": "a", "@type": "AgentNode", "agent_role": "Do", "objective": "A", "next": "b"},
                {"@id": "b", "@type": "AgentNode", "agent_role": "Do", "objective": "B"}
            ]
        }"#;
        let def = load_workflow_jsonld(json).unwrap();
        let dag = build_dag(&def).unwrap();
        assert!(!has_cycle(&dag));
        let order = topological_order(&dag).unwrap();
        assert_eq!(order.len(), 2);
        // Verify topology: a before b
        let idx_a = dag.node_index.get("a").unwrap();
        let idx_b = dag.node_index.get("b").unwrap();
        let pos_a = order.iter().position(|i| i == idx_a).unwrap();
        let pos_b = order.iter().position(|i| i == idx_b).unwrap();
        assert!(pos_a < pos_b, "a should come before b in topological order");
    }

    #[test]
    fn test_cycle_detection() {
        let json = r#"{
            "@id": "wf:cycle",
            "name": "Cycle",
            "description": "cycle test",
            "version": "1.0",
            "entry_node": "a",
            "nodes": [
                {"@id": "a", "@type": "AgentNode", "agent_role": "Do", "objective": "A", "next": "b"},
                {"@id": "b", "@type": "AgentNode", "agent_role": "Do", "objective": "B", "next": "a"}
            ]
        }"#;
        let def = load_workflow_jsonld(json).unwrap();
        let dag = build_dag(&def).unwrap();
        assert!(has_cycle(&dag));
    }

    #[test]
    fn test_condition_branch() {
        let json = r#"{
            "@id": "wf:branch",
            "name": "Branch",
            "description": "branch test",
            "version": "1.0",
            "entry_node": "a",
            "nodes": [
                {"@id": "a", "@type": "AgentNode", "agent_role": "Do", "objective": "A", "next": "b"},
                {"@id": "b", "@type": "AgentNode", "agent_role": "Do", "objective": "B",
                 "branch_on_failure": {"condition": "$.result.status == 'failed'", "target": "c"}},
                {"@id": "c", "@type": "AgentNode", "agent_role": "Act", "objective": "C"}
            ]
        }"#;
        let def = load_workflow_jsonld(json).unwrap();
        let dag = build_dag(&def).unwrap();
        assert!(!has_cycle(&dag));
        let order = topological_order(&dag).unwrap();
        assert_eq!(order.len(), 3);

        // Test should_branch
        let node_b = &dag.graph[*dag.node_index.get("b").unwrap()].def;
        let result = NodeResult {
            node_id: "b".to_string(),
            status: "failed".to_string(),
            summary: "failed".to_string(),
            archive_iri: None,
            turn_count: 0,
            tool_call_count: 0,
            error: Some("error".to_string()),
            output: None,
            artifacts: vec![],
        };
        let branch_target = should_branch(node_b, &result);
        assert_eq!(branch_target, Some("c".to_string()));

        // No branch on success
        let result_ok = NodeResult {
            status: "success".to_string(),
            ..result.clone()
        };
        let no_branch = should_branch(node_b, &result_ok);
        assert_eq!(no_branch, None);
    }
}
